import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mustapha Oyenuga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`bg-primary text-light ${inter.className}`}>
        <div className='min-h-screen max-w-screen-lg mx-auto px-4 font-sans py-12 md:px-0 md:py-16 lg:py-0'>
          {children}
        </div>
      </body>
    </html>
  );
}
