import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mustapha Oyenuga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`bg-primary-bg text-primary-text ${inter.className}`}>
        <div className="min-h-screen max-w-screen-xl mx-auto px-6 py-12 md:px-12 md:py-16 lg:py-0">
          {/* <Navbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
